### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by Fastbyte01**
Added the italian translation. May need some review.

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Hi,
Actually, the translations project is located [here](https://crowdin.com/project/protonmail).

Feel free to join and contribute out there! :)

**Comment by Fastbyte01** [comment]
Yes, I know and I have seen this later and already started to translate the
other things on crowdin. But this translation can be merged on crowdin to
not make all the work again.

Il 7 ago 2017 23:15, "Paul Feuvraux" <notifications@github.com> ha scritto:

**Comment by Super-Baleine** [comment]
Since it requires some review, I'm afraid it won't be merged...

**Comment by Fastbyte01** [comment]
Hi Paul, can I upload on crowdin and make from there the eventually little
things that my need a review or can you say me a way to test this review
locally?

Il 8 ago 2017 00:06, "Paul Feuvraux" <notifications@github.com> ha scritto:

**Comment by Super-Baleine** [comment]
Reviews are done by the proofreaders on crowdin, there are several proofreaders that approve or not translated strings. You cannot do the review by your own, it'd not make sense :)

That's our fault. We're not clear enough about this topic on GitHub. But translations are only managed on crowdin.

**Comment by Fastbyte01** [comment]
Yes, ok but to not lost all the work is possible for proofreader to review
this file and eventually after you integrate this in crowdin. I on crowdin
have almost finished the translation of the Android version of ProtonMail
but haven't seen to much people working on the Italian translation. If you
can add this can be a good thing and I can complete other translation
without working again on the web version.

Il 8 ago 2017 00:15, "Paul Feuvraux" <notifications@github.com> ha scritto:

**Comment by Super-Baleine** [comment]
I'm not in charge of the translations... Sorry. maybe someone else will answer you better than I did :)

**Comment by Super-Baleine** [comment]
Your modifications will be inserted in the translations on crowdin :)

**Pull request closed without merging**
