### PR TITLE
Make reply button automatically fetch latest draft

### PR DESCRIPTION
**Pull request by wheelie89**
Currently, when you click "Reply" whilst already having a draft in progress, it will create a new (empty) email.

Many mail clients do this differently, hitting the "Reply" button in Gmail for example will bring up the draft that you were previously composing.

This PR adds this functionality:

ProtonMail Reply Draft

I'm not sure what your policies regarding are, I'm doing this by passing down the `conversationID`, looking up the most recent draft via the new `useLastDraft()`, then passing that to `onCompose`.

If there is no previous draft, it will simply continue to do the "new empty message" thing that it's currently doing in production.

### CODE REVIEW

**Comment by wheelie89** [comment]
Oh and I'm not sure what the implications on `fromUndo` are - something with keeping the password around but idk much about email encryption, please tell me if that bit should be changed.

**Comment by Guillaumez** [comment]
Hello and thanks for your contribution !
This feature is not on our roadmap yet but discussions are ongoing about it.

Have a nice day !

**Comment by wheelie89** [comment]
Is there any place where users can ask you guys regarding whether you are generally open for contributions, whether you are considering a feature etc.?

We are thinking about moving our inbox from gmail to proton but it does seem lacking in some regards.

**Comment by wheelie89** [comment]
It's unfortunate there has been no further action to this. Our deadline is the following month in which we will probably settle with the paid gmail

**Pull request closed without merging**
