### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Super-Baleine**
All cases are not translated.

### CODE REVIEW

**Comment by Super-Baleine** [comment]
I don't know if it's "Label" or "Libellé"...

**Comment by emersion** [comment]
Maybe "Étiquette"

**Comment by Super-Baleine** [comment]
Hmm, it's ugly, and i think "Étiquette" it's better for a milk bottle than an user interface in computing :')

**Comment by Super-Baleine** [comment]
And also this : 
imgpsh_fullsize

it would not be better to recommend Chromium instead of Chrome ? Chrome is Google, PM is against this company which eat our privacy... Where's the coherence ? x)

**Pull request closed without merging**
